language: ruby

cache: bundler

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.6"
  - "2.3.3"
  - "2.4.0"

gemfile:
  - Gemfile
  - gemfiles/activesupport-4.gemfile
  
before_install:
  - gem update bundler
